### ISSUE TITLE
Checking for example or examples

### ISSUE THREAD

**Issue by savage-alex** [openapi-contrib/style-guides#12]
I have the following rule that is asking my designers to add examples for query params:

```adv-query-parameters-example-exists:
    description: All query parameters SHOULD have an example.
    severity: error
    message: 'All query parameters SHOULD have an example.'
    given: "$..parameters[?(@.in == 'query')]"
    then:
      field: example
      function: truthy
```

I would also like it to accept when a designer has included "examples" as well (Hopefully through an OR field+truthy)

OAS syntax for multiple examples:
```
parameters: 
        - name: employeeId
          description: A filter to include one or more employees' absences. A maximum of 20 employees' absences can be requested. The absences are grouped by employee.
          required: false
          in: query
          schema:
            type: string
          style: form
          explode: false
          examples:
            oneId:
              value: A1234
            multipleIds:
              value: A12134,A13,M12334
```

Is this something you have thought of as a good rule?
